services:
  # Development Jupyter environment with live code updates
  jupyter-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8081:8081"
    volumes:
      # Mount the entire project for live updates
      - .:/usr/src/app
      # Cache pip installs to speed up container rebuilds
      - jupyter-dev-cache:/root/.cache/pip
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - PYTHONPATH=/usr/src/app
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    command: ["jupyter", "lab", "--ip=0.0.0.0", "--port=8081", "--no-browser", "--allow-root", "--NotebookApp.token=''", "--NotebookApp.password=''", "--NotebookApp.allow_origin='*'"]

  # Development Streamlit app with live code updates  
  streamlit-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8501:8501"
    volumes:
      - .:/usr/src/app
      - streamlit-dev-cache:/root/.cache/pip
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - PYTHONPATH=/usr/src/app
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    command: ["streamlit", "run", "app/pages/Home.py", "--server.port=8501", "--server.address=0.0.0.0", "--server.runOnSave=true"]

  # Interactive development shell
  dev-shell:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/usr/src/app
      - shell-dev-cache:/root/.cache/pip
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - PYTHONPATH=/usr/src/app
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    command: ["bash"]
    stdin_open: true
    tty: true

volumes:
  jupyter-dev-cache:
  streamlit-dev-cache:
  shell-dev-cache: