_wandb:
    value:
        cli_version: 0.21.1
        e:
            sahfvp55pdsnumvqirtxp7bkch38osq9:
                cpu_count: 16
                cpu_count_logical: 32
                cudaVersion: "12.1"
                disk:
                    /:
                        total: "1081101176832"
                        used: "59995238400"
                email: dadman.shayan@gmail.com
                executable: /opt/conda/bin/python
                git:
                    commit: bfcbaef7d76afa93d0e309108b50af7c11ccb3c5
                    remote: git@github.com:dadmaan/music-anomalizer.git
                gpu: NVIDIA GeForce RTX 4090 Laptop GPU
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ada
                      memoryTotal: "17171480576"
                      name: NVIDIA GeForce RTX 4090 Laptop GPU
                      uuid: GPU-3907daea-b16f-211e-4297-0f3473255012
                host: 79d136b711bb
                memory:
                    total: "33501962240"
                os: Linux-5.15.146.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
                program: <python with no main file>
                python: CPython 3.11.12
                root: .
                startedAt: "2025-08-21T10:40:15.688867Z"
                writerId: sahfvp55pdsnumvqirtxp7bkch38osq9
        m:
            - "1": trainer/global_step
              "6":
                - 3
              "7": []
            - "2": '*'
              "5": 1
              "6":
                - 1
              "7": []
        python_version: 3.11.12
        t:
            "1":
                - 1
                - 5
                - 9
                - 11
                - 41
                - 49
                - 53
                - 103
            "2":
                - 1
                - 5
                - 9
                - 11
                - 41
                - 49
                - 53
                - 103
            "3":
                - 1
                - 2
                - 7
                - 13
                - 66
            "4": 3.11.12
            "5": 0.21.1
            "6": 4.55.2
            "12": 0.21.1
            "13": linux-x86_64
bias:
    value: false
dropout_rate:
    value: 0.2
hidden_dims:
    value:
        - 512
        - 256
        - 128
        - 64
        - 32
learning_rate:
    value: 1e-05
num_features:
    value: 1024
train_data_length:
    value: 1816
use_batch_norm:
    value: true
weight_decay:
    value: 1e-05
